[package]
name = "wasm"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
rustscan = { path = "../rustscan" }
js-sys = "0.3.77"
wasm-bindgen-futures = "0.4.50"
